### ISSUE TITLE
Constructors don't seem to get patched in a patch_<name> class

### ISSUE THREAD

**Issue by BobTheBob9** [0x0ade/MonoMod#51]
I've been trying to patch a class from [GILES](https://github.com/Unity-Technologies/giles/), specifically `GILES.Serialization.pb_SceneNode`, in order to do this, i've been trying to patch the constructor, but according to a decompile, the constructors don't actually get patched, while any other non-constructor methods i've targeted do (e.g. `GetObjectData()` gets patched fine, constructors do not).  
Here's my code i'm trying to patch in 
```cs
namespace GILES.Serialization {
    public class patch_pb_SceneNode : ISerializable {
        public string name;
        public pb_Transform transform;
        public List<pb_SceneNode> children;
        public pb_MetaData metadata;
        public List<pb_ISerializable> components;
        public List<string> customComponents;
        public patch_pb_SceneNode(GameObject root) {
            name = root.name;
            components = new List<pb_ISerializable>();
            customComponents = new List<string>();
            foreach (MonoBehaviour mono in root.GetComponents<MonoBehaviour>()) {
                foreach (object attribute in mono.GetType().GetCustomAttributes(true)) {
                    if (attribute.GetType() == typeof(GTTOD.LevelEditor.CustomEditorObject)) {
                        customComponents.Add(attribute.GetType().AssemblyQualifiedName);
                    }
                }
            }
            pb_MetaDataComponent pb_MetaDataComponent = root.GetComponent<pb_MetaDataComponent>();
            if (pb_MetaDataComponent == null) {
                pb_MetaDataComponent = root.AddComponent<pb_MetaDataComponent>();
            }
            metadata = pb_MetaDataComponent.metadata;
            if (metadata.assetType == AssetType.Instance) {
                foreach (Component component in root.GetComponents<Component>()) {
                    if (!(component == null) && !(component is Transform)) {
                        if (!component.GetType().GetCustomAttributes(true).Any((object x) => x is pb_JsonIgnoreAttribute)) {
                            components.Add(pb_Serialization.CreateSerializableObject<Component>(component));
                        }
                    }
                }
            }
            transform = new pb_Transform();
            transform.SetTRS(root.transform);
            children = new List<pb_SceneNode>();
            foreach (object obj in root.transform) {
                Transform transform = (Transform)obj;
                if (transform.gameObject.activeSelf) {
                    children.Add(new pb_SceneNode(transform.gameObject));
                }
            }
        }
        public patch_pb_SceneNode(SerializationInfo info, StreamingContext context) {
            name = (string)info.GetValue("name", typeof(string));
            customComponents = (List<string>)info.GetValue("customComponents", typeof(List<string>));
            transform = (pb_Transform)info.GetValue("transform", typeof(pb_Transform));
            children = (List<pb_SceneNode>)info.GetValue("children", typeof(List<pb_SceneNode>));
            metadata = (pb_MetaData)info.GetValue("metadata", typeof(pb_MetaData));
            if (metadata.assetType == AssetType.Instance) {
                components = (List<pb_ISerializable>)info.GetValue("components", typeof(List<pb_ISerializable>));
            }
        }

        public extern void orig_GetObjectData(SerializationInfo info, StreamingContext context);
        public void GetObjectData(SerializationInfo info, StreamingContext context) {
            info.AddValue("customComponents", customComponents, typeof(List<string>));
            orig_GetObjectData(info, context);
        }
    }
}

**Comment by 0x0ade** [comment]
Mark your constructors with the `[MonoModConstructor]` attribute. This is required for a few reasons:
1. All field initialization is compiled into the constructor, before the base constructor runs. Replacing the ctor means that you're responsible for initializing all fields, unless you run the original ctor.
2. The C# compiler doesn't let you move or skip the base constructor call. When your patch inherits the original class (`patch_A : A`), this results in the patch ctor calling the patched ctor, thus endless recursion. You'll either need to make your patch class inherit the original class' base class (`A : B`, `patch_A : B`), or run the original ctor.
3. The constructor method name is `.ctor`, which makes defining an `orig` method harder than usual (you wouldn't be able to reliably call it due to point 2 anyway).
4. Even if you don't know about any of that and don't implement a custom constructor, the C# compiler will create an "empty" default ctor which would fully replace the original ctor by accident.

Sadly, there is no way for MonoMod to guess what part of the .mm.dll is part of your patch, and what is C# "compiler garbage" which could break everything. That's why MonoMod ignores all constructors by default.

If you know that your constructors won't have any side effects, adding the `[MonoModConstructor]` attribute is enough. Otherwise, feel free to take a look at how to use the attribute to mark a non-constructor method as a constructor, which gives you full control over what code runs in it: https://github.com/EverestAPI/Everest/blob/master/Celeste.Mod.mm/Patches/Decal.cs

I'll close this "issue" as it's not a problem with MonoMod itself (although I wish I could handle constructors better), but feel free to continue asking questions either here or on Discord.

**Comment by BobTheBob9** [comment]
ah, i had no idea, thanks!
